#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Project Euler 2

Each new term in the Fibonacci sequence is generated by adding the previous 
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values 
do not exceed four million, find the sum of the even-valued terms.
"""

a_2 = 1
a_1 = 1
a_3 = a_2 + a_1
sum = 0

while a_3 < 4000000:
    # print(a_3,sum)
    if a_3 % 2 == 0: sum = sum + a_3
    a_2 = a_1
    a_1 = a_3
    a_3 = a_1 + a_2
    
print(sum)



